### ISSUE TITLE
Merge Pull Request on non-default branch , but still not able auto close issue

### ISSUE THREAD

**Issue by zigang93** [ldez/gha-mjolnir#7]
Below is my yml file for github actions

```
name: Close issues related to a merged pull request from dev branches.

on:
  pull_request:
    branches:
      - dev

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I am already try create a pull request with commit message "Fix #30 xxx" into `dev` branch ( not default branch ) and approve the merge.. but it still not able to close my #30 issue after merge success.

need some help.. thanks.

**Comment by ldez** [comment]
Hello,

mjolnir is based on the PR description, it doesn't work with commit message.

**Comment by zigang93** [comment]
![Screenshot 2020-09-04 at 9 29 59 AM](https://user-images.githubusercontent.com/11520821/92189596-b0142400-ee91-11ea-9a43-c7a23d6c06f5.png)

This is the screenshot from my private org repo
After merge, still cannot close the issue yet.

**Comment by ldez** [comment]
Could you provide the logs?

**Comment by zigang93** [comment]
Unfortunately, I couldn't able to provide any logs. 
because the github action never start the workflow when i merge pull request to my `dev` branch

I am not sure what am I doing wrong or misunderstand something..
I am trying to create a public repo to reproduce the issue soon.

**Comment by zigang93** [comment]
@ldez 
Hi, this is my public repo
[link](https://github.com/zigang93/test-auto-close-issue-workflow/pulls)

as you can see.. 
I am create pull request from `fork_repo` to `dev` branch
after success merge into `dev`
still not able to close the issue that I created

**Comment by ldez** [comment]
Could you try:

```yaml
name: Close issues related to a merged pull request from dev branches.

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: ldez/gha-mjolnir@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onevent_nametypes
- https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
